/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/n.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/n.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_id40.geometry} material={materials['132']} position={[0.291, 0.108, 0.295]} scale={[0.703, 0.409, 0.001]} />
      <mesh geometry={nodes.mesh_id42.geometry} material={materials['134']} position={[-0.133, -0.07, 0.309]} scale={[0.675, 0.387, 0.001]} />
      <mesh geometry={nodes.mesh_id44.geometry} material={materials['136']} position={[0.39, -0.155, 0.325]} scale={[0.556, 0.319, 0.001]} />
      <mesh geometry={nodes.mesh_id57.geometry} material={materials['146']} position={[-0.411, -0.169, 0.359]} scale={[0.494, 0.276, 0.001]} />
      <mesh geometry={nodes.mesh_id59.geometry} material={materials['148']} position={[-0.346, 0.137, 0.3]} scale={[0.668, 0.379, 0.001]} />
    </group>
  )
}

useGLTF.preload('/n.glb')
